name: Run API unit tests
on:
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: /tmp/lib/python3.8/site-packages
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: install
      run: |
        python3 -m pip install onnxruntime-training
        python3 setup.py install --prefix=/tmp
    - name: Run tests
      run: |
        echo `python3 --version`
        python -m pytest -sv tests/torch-ort_test_api.py
        python -m pytest -sv tests/experimental/torch_ort_graph_config_tests.py
        python -m pytest -sv tests/experimental/torch_ort_json_config_tests.py
    - name: Print test message
      run: echo Running torch-ort API unit tests
